
trigger:
 - master

pool:
  name: 'Hosted Windows 2019 with VS2019'

steps:
 - pwsh: |
     $url = "https://downloads.arduino.cc/arduino-1.8.10-windows.zip"
     Invoke-WebRequest -Uri $url -OutFile "arduino.zip"
     [System.IO.Compression.ZipFile]::ExtractToDirectory("arduino.zip", "arduino")
